[package]
name = "vbot"
version = "0.1.0"
edition = "2024"

[dependencies]
poise = "0.6.1"
shuttle-runtime = "0.52.0"
shuttle-serenity = "0.52.0"
tokio = { version = "1.44.0", features = ["macros", "rt-multi-thread"] }
tracing = "0.1.41"
